//
// Created by fedemeister on 14/03/18.
//

#include "Fecha.hpp"

Fecha::Fecha(int dia, int mes, int anyo) {

}

// A partir de una cadena de caracteres de bajo nivel en el formato "dd/mm/aaaa"
Fecha::Fecha(const char *) {

}


//GETTERS GENERATED BY CLION
int Fecha::getDia() const {
    return dia;
}

int Fecha::getMes() const {
    return mes;
}

int Fecha::getAnyo() const {
    return anyo;
}
